// Public API for `@/app/_data/hikes`. All exports are explicit (no `export *`)
// so future type/symbol drift surfaces immediately.
export {
  acceptHikePhotoTrackTimeMatchCandidate,
  attachCreatorTrackToHike,
  attachPhotoToHike,
  attachTrackToHike,
  cancelHikeInvitation,
  clearHikePhotoCaptureTimezone,
  confirmHikePhotoCaptureTimezone,
  contributePhotoToHike,
  createHike,
  createHikeNote,
  createTrackAndAttachToHike,
  deleteHike,
  deleteHikeNote,
  detachPhotoFromHike,
  detachTrackFromHike,
  inviteHikeParticipant,
  likeHikePhoto,
  refreshHikePhotoExifMetadata,
  rejectHikePhotoMapCoordinate,
  removeHikeParticipant,
  reorderHikePhotos,
  respondToHikeInvitation,
  unlikeHikePhoto,
  updateHike,
  updateHikeNote,
} from "./mutations";
export {
  getAllHikes,
  getHikeById,
  getHikeParticipantManagementBySlug,
  getHikePhotoContributionCapabilityBySlug,
  getHikePhotoDetail,
  getHikePhotoOptions,
  getHikeTrackContributionCapability,
  getMyLikedHikePhotos,
  getPendingHikeInvitations,
  getPublicHikeBySlug,
  getPublicHikePhotoLikeStates,
  getPublicHikes,
  getPublicTripCreationCapability,
  isAcceptedHikeParticipant,
} from "./queries";
export type {
  CreateTrackAndAttachToHikeInput,
  CreateTrackAndAttachToHikeResult,
  HikeActionValues,
  HikeListItem,
  HikeParticipantManagement,
  HikePhotoAcceptedCoordinate,
  HikePhotoContributionCapability,
  HikePhotoContributionValues,
  HikePhotoDetail,
  HikePhotoLikeState,
  HikePhotoOption,
  HikeTrackContributionCapability,
  HikeTrackOption,
  MyLikedHikePhoto,
  PendingHikeInvitation,
  PublicHike,
  PublicHikeListItem,
  PublicTripCreationCapability,
} from "./types";
